### ISSUE TITLE
update the tag to 0.0.7

### ISSUE THREAD

**Issue by maruilian11** [l-lin/font-awesome-animation#11]
hi, could you please update the tag to v0.0.7 so that we can add your lib on https://cdnjs.com with **git auto-update**
https://github.com/cdnjs/cdnjs/pull/5949

**Comment by l-lin** [comment]
Here you go: https://github.com/l-lin/font-awesome-animation/releases/tag/v0.0.7 :smile:

**Comment by maruilian11** [comment]
thank you very much !
