### ISSUE TITLE
NPM Installation Package

### ISSUE THREAD

**Issue by mikebronner** [l-lin/font-awesome-animation#13]
I tried installing it via NPM, but all the grunt dependencies caused me to give up (they aren't installed automatically anymore with NPM 3). Is there a way to install it without requiring Grunt for those that don't use it?

Thanks :)

**Comment by felicienfrancois** [comment]
using bower: http://bower.io/

**Comment by calcerrada** [comment]
So I can not install directly from npm ? I use npm , and do not want to have two package managers.

Please add to npm!!

**Comment by felicienfrancois** [comment]
font-awesome-animation is also published to npm.
You just need to execute:
```
npm install font-awesome-animation --save
```

then the files are in `node_modules/font-awesome-animation/dist`

**Comment by l-lin** [comment]
Thanks @felicienfrancois :)
