### ISSUE TITLE
Bad package.json version

### ISSUE THREAD

**Issue by felicienfrancois** [l-lin/font-awesome-animation#16]
When installing with bower I get the following warning:
```bower font-awesome-animation#0.0.8    mismatch Version declared in the json (0.0.7) is different than the resolved one (0.0.8)```

This is due to the package.json version have not been bumped to 0.0.8

**Comment by l-lin** [comment]
Done with those PR: #17 & #18 .

**Comment by skecskes** [comment]
thanks :+1:
