### ISSUE TITLE
Pause before repeat

### ISSUE THREAD

**Issue by eggboxio** [l-lin/font-awesome-animation#19]
A feature request. Would be great if a class could be added that would pause the animation before it repeated.

This would presumably mean changing the keyframes for each animation but SASS could help here.

**Comment by eggboxio** [comment]
I have solved this feature request: http://waitanimate.eggbox.io/
Hope you don't mind but I've used your animations as the example and have credited you.

**Comment by l-lin** [comment]
Sorry for the late answer, I have been busy (still am). Awesome projet you got here :+1:

**Comment by eggboxio** [comment]
Thanks. I've submitted it to several sites but not received any feedback yet. If you have ideas or concerns then I'd love to know.
