### ISSUE TITLE
Just a request :)

### ISSUE THREAD

**Issue by nbelley** [l-lin/font-awesome-animation#30]
Hi! I was wondering if it was possible to have an inverted  faa-falling animation? Going up? 

Thanks for your good work in any case!

**Comment by l-lin** [comment]
Done in [0.3.0](https://raw.githubusercontent.com/l-lin/font-awesome-animation/0.3.0/dist/font-awesome-animation.min.css).

**Comment by nbelley** [comment]
Thanks!
