### ISSUE TITLE
Horizontal Reversed

### ISSUE THREAD

**Issue by manattweb** [l-lin/font-awesome-animation#33]
What would be the proper way to implement a horizontal reversed where the movement is to the left instead of the right. I've tried to add it by copying horizontal and changing the X value to -5px; however, it doesn't move. I tried adding 5px of padding to the left of the <i> and to the parent container thinking there wasn't room over there, but it still doesn't move.

Is this possible? If so, can you point me in the right direction. I'm wanting an arrow to move to the left to indicate something has to be one over there.

**Comment by l-lin** [comment]
Sorry for the long delay. I added a CSS class `faa-reverse` you can use along with `faa-horizontal` to have the reverse effect.

It's available on [v1.1.0](https://github.com/l-lin/font-awesome-animation/releases/tag/v1.1.0).
