### ISSUE TITLE
NPM package?

### ISSUE THREAD

**Issue by ttodua** [l-lin/font-awesome-animation#34]
Is this the official npm package by this repo/author?
https://www.npmjs.com/package/font-awesome-animation

**Comment by skecskes** [comment]
yes, that is correct

**Comment by ttodua** [comment]
ok, would be nice if in this repo readme it was stated too (instead of bowerJS - npm install)..

**Comment by skecskes** [comment]
I don't own this repo, I just put it onto npm. I think you can raise PR and when repo owner accepts it, we can update npmjs package

**Comment by ttodua** [comment]
The issue is that i've tried `npm install font-awesome-animations` and it screws up the project and can't run afterwards.  well, i'll ignore this.

**Comment by jonnsn** [comment]
How can the owner be contacted? I can only see your name as collaborator.
It would be nice if the package could include scss source as well...

**Comment by l-lin** [comment]
@skecskes, can you add me to the NPM project please?

**Comment by skecskes** [comment]
@l-lin you are already maintainer. I added you long time ago.
![font-awesome-animation_-_npm](https://user-images.githubusercontent.com/3411329/105179452-471c0880-5b21-11eb-8908-bdd094012cc4.gif) Maybe you just need to push new version of library with your credentials. Let me know if that works for you, or I can just push latest 0.3.0 version if you want.

**Comment by jonnsn** [comment]
Ah now I got the who is who right ;) Thank you both!

**Comment by l-lin** [comment]
Thank you @skecskes, I did not check I was also a maintainer on the NPM project. Just published the v0.3.0.

@jonnsn, I created the adequate issue: #35. I should have time to do it this week.
