### ISSUE TITLE
Font awesome animation in WordPress

### ISSUE THREAD

**Issue by pevoje** [l-lin/font-awesome-animation#9]
Hi,

I've tried using animation of font awesome in WP widget, but couldn't get it to work.

I've used as instructed but no results, as you can see tried it on parent element also:

```
<a href="#" class="faa-parent animated-hover"><i class="fa fa-facebook faa-facebook fa-4x social-icon"></i></a>
<a href="#"><i class="fa fa-twitter faa-twitter animated-hover fa-4x social-icon"></i></a>
<a href="#"><i class="fa fa-linkedin faa-linkedin animated-hover fa-4x social-icon"></i></a>
<a href="#"><i class="fa fa-google-plus faa-google-plus animated-hover fa-4x social-icon"></i></a>
```

Any advice?

**Comment by l-lin** [comment]
`faa-facebook`, `faa-twitter`, `faa-linkedin` and `faa-google-plus` are not animations.
Use the ones that are in the [gh-pages](http://l-lin.github.io/font-awesome-animation/).
For example:
```html
<a href="#"><i class="fa fa-twitter faa-pulse animated-hover fa-4x social-icon"></i></a>
```

**Comment by pevoje** [comment]
I thought all icons from font awesome can use the animations. Thanks for the reply

**Comment by l-lin** [comment]
You can use animations for everything. You need to specify wich animation you want for the icon.
For example, if I want to shake the twitter icon, you need to add the class `faa-shake` like this:
```html
<a href="#"><i class="fa fa-twitter faa-shake animated-hover fa-4x social-icon"></i></a>
```
If you want to bounce the twitter icon, you need to add the class `faa-bounce` like this:
```html
<a href="#"><i class="fa fa-twitter faa-bounce animated-hover fa-4x social-icon"></i></a>
```
